In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from statsmodels.tsa.arima.model import ARIMA

model_data = pd.read_csv(
    r"C:\Users\Adity\OneDrive\Desktop\RESEARCH\Project Work\Inflation-Forecasting-Dashboard\data\processed\model_sample_cpi_wpi.csv",
    parse_dates=["date"]
)

model_data = (
    model_data
    .sort_values("date")
    .reset_index(drop=True)
)

display(model_data.head())
display(model_data.tail())

,date,cpi_combined,cpi_yoy,wpi_all,wpi_primary,wpi_fuel,wpi_manufacturing,wpi_all_yoy,wpi_primary_yoy,wpi_fuel_yoy,wpi_manufacturing_yoy,output_ppi,output_ppi_yoy
0,2024-04-01,186.7,4.828748,99.9,108.8,92.0,98.5,0.909091,6.666667,-2.127660,-0.605449,99.7,0.605449
1,2024-05-01,187.7,4.801787,100.4,110.1,91.7,98.9,1.825558,7.624633,0.328228,0.000000,100.1,1.521298
2,2024-06-01,190.2,5.082873,100.7,111.8,89.9,99.1,2.441506,8.228461,-0.662983,0.916497,100.4,2.240326
3,2024-07-01,193.0,3.596350,101.0,113.1,91.2,98.8,1.917255,4.819277,0.662252,1.022495,100.8,1.715439
4,2024-08-01,193.0,3.651987,100.8,113.8,90.9,98.4,1.306533,5.370370,-0.980392,0.305810,100.7,1.307847

,date,cpi_combined,cpi_yoy,wpi_all,wpi_primary,wpi_fuel,wpi_manufacturing,wpi_all_yoy,wpi_primary_yoy,wpi_fuel_yoy,wpi_manufacturing_yoy,output_ppi,output_ppi_yoy
23,2026-03-01,NaN,3.125000,104.6,111.4,93.5,104.7,3.976143,2.578269,3.200883,4.804805,104.9,4.170804
24,2026-04-01,NaN,2.803738,108.9,112.8,111.0,107.0,8.358209,3.963134,25.000000,6.679960,108.8,8.258706
25,2026-05-01,NaN,2.590674,110.1,114.0,113.4,108.0,9.880240,5.263158,30.795848,7.676969,109.9,9.680639
26,2026-06-01,NaN,1.956746,110.2,116.1,111.1,107.8,9.870389,7.004608,27.408257,7.477567,109.9,9.571286
27,2026-07-01,NaN,0.968893,110.0,117.2,105.4,108.4,9.780439,8.518519,20.045558,8.291708,109.9,9.571286